### ISSUE TITLE
[question]请问这个是否支持miui12.5？另外，安装这个之后，设置页面和权限管理是本地化的么？

### ISSUE THREAD

**Issue by TurnOffNOD** [MonwF/mipay-extract#3]
请问这个方案是否支持miui12.5？
另外，安装这个之后，设置页面和权限管理是本地化的么？

**Comment by MonwF** [comment]
支持12.5，设置和权限都是欧版不变

**Comment by TurnOffNOD** [comment]
> 
> 
> 支持12.5，设置和权限都是欧版不变

哦，搭配xposed模块也是这样么？

**Comment by MonwF** [comment]
> > 支持12.5，设置和权限都是欧版不变
> 
> 哦，搭配xposed模块也是这样么？

我的xposed模块不改设置和权限 自用为主

**Comment by TurnOffNOD** [comment]
> 
> 
> > > 支持12.5，设置和权限都是欧版不变
> > 
> > 
> > 哦，搭配xposed模块也是这样么？
> 
> 我的xposed模块不改设置和权限 自用为主

国内版权限要用来对付国产app流氓。
国内版设置其实是为了“设置-双卡与移动网络-5G网络”这个设置项。
所以多问了两句……
